project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from main import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),

    #url(r'^state_detail/(?P<name>.+)/$', 'main.views.state_detail'),
    # url(r'^get_post/$', 'main.views.get_post'),
    # url(r'^get_search/$', 'main.views.get_search'),
    # url(r'^GetPost/$', views.GetPost.as_view()),
    # url(r'^template_view/$', 'main.views.template_view'),

    #reg views
    url(r'^state_list/$', 'main.views.state_list'),
    url(r'^state_detail/(?P<pk>.+)$', 'main.views.state_detail'),

    #cbv views
    url(r'^cbv_list/$', views.StateListView.as_view()),
    url(r'^cbv_detail/(?P<pk>[0-9]+)/$', views.DetailView.as_view()),

    url(r'^city_search/$', 'main.views.city_search'),

    url(r'^city_create/$', 'main.views.city_create'),

    url(r'^city_edit/(?P<pk>[0-9]+)/$', 'main.views.city_edit'),

    url(r'^city_delete/(?P<pk>[0-9]+)/$', 'main.views.city_delete'),



]

main/models.py
from django.db import models

# Create your models here.
class State(models.Model):
	abbreviation = models.CharField(max_length=2, null=True, blank=True)
	name = models.CharField(max_length=100, null=True, blank=True)
	#city1 = models.CharField(max_length=100)


	def __unicode__(self):
		return "%s" % self.name 

	
class StateCapital(models.Model):
	name = models.CharField(max_length=100, null=True, blank=True)

	state = models.OneToOneField('main.State', null=True)

	latitude = models.FloatField(null=True, blank=True)
	longitude = models.FloatField(null=True, blank=True)
	capital_population = models.IntegerField(null=True, blank=True)

	def __unicode__(self):
		return self.name

class City(models.Model):
	name = models.CharField(max_length=255, null=True, blank=True)
	zipcode =models.IntegerField(null=True, blank=True)
	county = models.CharField(max_length=255, null=True, blank=True)
	state = models.ForeignKey('main.State', null=True)
	latitude = models.FloatField(null=True, blank=True)
	longitude = models.FloatField(null=True, blank=True)

	def __unicode__(self):
		return self.name

main/forms.py
from django import forms 
from main.models import City 

from django.core.validators import RegexValidator

alphanumeric = RegexValidator(r'^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')


class CitySearchFrom(forms.Form):
	name = forms.CharField(required=True, initial='Orem', validators=[alphanumeric])
	state = forms.CharField(required=True, initial='Utah', validators=[alphanumeric])

class CreateCityForm(forms.ModelForm):
	class Meta:
		model = City 
		fields = '__all__'

class CityEditForm(forms.ModelForm):
    class Meta:
        model = City
        fields = '__all__'
   

main/views.py
from django.shortcuts import render, render_to_response 
from django.template import RequestContext
#from django.http import HttpResponse
from main.models import State, City
# from django.views.decorators.csrf import csrf_exempt
# from django.views.generic import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required

#this is a comment

#forms
from main.forms import CitySearchFrom, CreateCityForm, CityEditForm

# Create your views here.
@login_required
def city_delete(request, pk):

	City.objects.get(pk=pk).delete()

	return redirect('/city_search/')

@login_required
def city_edit(request, pk):

	print 'REQUEST TYPE -- %s' % request.method

	request_context = RequestContext(request)
	context = {}

	form = CityEditForm(request.POST or None)

	city = City.objects.get(pk=pk)

	form = CityEditForm(request.POST or None, instance=city)

	context['form'] = form

	if form.is_valid():
		form.save()

		return redirect('/city_search/')

	return render_to_response('city_edit.html', context, context_instance=request_context)





def city_create(request):
	request_context = RequestContext(request)
	context = {}

	if request.method == 'POST':
		form = CreateCityForm(request.POST)
		context['form'] = form

		if form.is_valid():
			form.save()

			return render_to_response('city_create.html', context, context_instance=request_context)
		else:
			context['valid'] = form.errors
			return render_to_response('city_create.html', context, context_instance=request_context)
	else:
		form = CreateCityForm()
		context['form'] = form		
		return render_to_response('city_create.html', context, context_instance=request_context)




def city_search(request):
	request_context = RequestContext(request)

	context = {}

	if request.method == 'POST':
		form = CitySearchFrom(request.POST)
		context['form'] = form

		if form.is_valid():
			name = '%s' % form.cleaned_data['name']
			state = form.cleaned_data['state']
# , means and [this is to allow us to search for the name of the city and state]
			context['city_list'] = City.objects.filter(name__startswith=name, state__name__startswith=state)

			return render_to_response('city_search.html', context, context_instance=request_context)

		else:
			context['valid'] = forms.errors

	else:
		form = CitySearchFrom()
		context['form'] = form
		return render_to_response('city_search.html', context, context_instance=request_context)


def state_list(request):
	context = {}
	states = State.objects.all()
	context['states'] = states
	return render(request, 'state_list.html', context)


class StateListView(ListView):
	model = State
	template_name = 'state_list.html'
	context_objects_name = 'states'

def state_detail(request, pk):
	context = {}
	state = State.objects.get(pk=pk)
	context['state'] = state
	return render(request, 'state_detail.html', context)

class StateDetailView(DetailView):
	model = State
	template_name = "state_detail.html"
	context_objects_name = "state"

	# state_list = []

	# for state in states:
	# 	try:
	# 		state_list.append("<a href= '/state_detail/%s'> %s -- %s</a><br>" % ( state.name, state.name, state.StateCapital.name))
	# 	except Exception, e:
	# 		print e

	# return HttpResponse(state_list)

# def template_view(request):

# 	context = {}

# 	states = State.objects.all()

# 	context['states'] = states

# 	return render(request,'state_list.html', context)


c
# @csrf_exempt
# def get_search(request):

# 	print request.method

# 	if request.method == 'GET':

# 		text_string = ''

# 		text_string += """
# 		<form action="/get_search/" method="POST">

# 		Search Cities:
# 		<input type='text' name='city_name'>
# 		<br>

# 		<input type='submit' value="Submit">

# 		</form>

# 		"""
# 		return HttpResponse(text_string)

# 	if request.method == 'POST':

# 		city_name = request.POST.get('city_name', None)

# 		print 'GET: %s' % request.GET
# 		print 'POST: %s' % request.POST

# 		text_string = ''
# 		text_string += 'Search Term: %s <br>' % city_name

# 		text_string += """
# 		<form action="/get_search/" method="POST">

# 		Search Cities:
# 		<input type='text' name='city_name'>
# 		<br>

# 		<input type='submit' value="Submit">

# 		</form>

# 		"""



# 	if city_name != None:
# 		cities = City.objects.filter(name__icontains=city_name)
# 		for city in cities:
# 			text_string += '%s <br>' % city.name
# 	return HttpResponse(text_string)


# class GetPost(View):
	
# 	def get(self, request, *args, **kwargs):
# 		text_string = ''

# 		text_string += """
# 		<form action="/GetPost/" method="POST">

# 		Search Cities:
# 		<input type='text' name='city_name'>
# 		<br>

# 		<input type='submit' value="Submit">

# 		</form>

# 		"""
# 		return HttpResponse(text_string)


# 	def post(self, request, *args, **kwargs):
# 		city_name = request.POST.get('city_name', None)

# 		print 'GET: %s' % request.GET
# 		print 'POST: %s' % request.POST

# 		text_string = ''
# 		text_string += 'Search Term: %s <br>' % city_name

# 		text_string += """
# 		<form action="/GetPost/" method="POST">

# 		Search Cities:
# 		<input type='text' name='city_name'>
# 		<br>

# 		<input type='submit' value="Submit">

# 		</form>
# 		"""
# 		return HttpResponse(text_string)




# @csrf_exempt
# def get_post(View):

# 	city_name = request.GET.get('q', None)

# 	post_var = request.POST.get('q', None)

# 	print request.GET
# 	print request.POST

# 	text_string = ''

# 	text_string += 'Get Var: %s <br>' % city_name

# 	text_string += 'Post Var: %s <br>' % post_var

# 	text_string += """
# 	<form action="/get_post/" method="POST">

# 	Enter Var:
# 	<input type='text' name='q'>
# 	<br>

# 	<input type='submit' value="Submit">
# 	</form>
# 	"""
# 	return HttpResponse(text_string)

main/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>  
<html>  
<head>
 <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>States</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
	<link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}" >

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/business-casual.css' %}" >

    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">





<title>Page Title</title>  

</head>  
    <body>

    <div class="brand">US STATES</div>
    <div class="address-bar">CODED | spring'16</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="index.html">Option 1</a>
                    </li>
                    <li>
                        <a href="about.html">Option 2</a>
                    </li>
                    <li>
                        <a href="blog.html">Option 3</a>
                    </li>
                    <li>
                        <a href="contact.html">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    {% block body %}
    {% endblock %}

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>


	<script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>  
	<script src="{% static 'js/bootstrap.min.js' %}"></script>     

    </body>
</html>  

main/templates/city_create.html
{% extends 'base.html' %}

{% block body %}

<form method='POST' action='/city_create/'>
{% csrf_token %}

{{ form.as_p }}

<input type='submit' value='save'>

</form>

{% endblock %}

main/templates/city_edit.html
{% extends 'base.html' %}

{% block body %}

<form method='POST' action='/city_edit/{{ city.pk }}/'>
{% csrf_token %}

{{ form.as_p }}

<input type='submit' value='Save'>

</form>

{% endblock %}

main/templates/city_search.html
{% extends 'base.html' %}

{% block body %}

	<form method='POST' action='/city_search/' style='color:CCC'>
		{% csrf_token %}

		{{ form.as_table }}

		<input type='submit' value='Search' />

	</form>

	{% for city in city_list %}
		<span>
			{{ city.name }}
			{% if request.user.is_authenticated %}
			<a href='/city_edit/{{ city.pk }}/'>| -- EDIT -- |</a>
			<a href='/city_delete/{{ city.pk }}/'>| -- DELETE -- |</a>
			{% endif %}

		</span>
		<br/>

	{% endfor %}

{% endblock %}

main/templates/state_detail.html
{% extends 'base.html' %}

{% block body %}

	<div class="container">
	 	<div class="row">
	            <div class="box">
	                <div class="col-lg-12">
	                    <hr>
	                    <h2 class="intro-text text-center">
	                        <strong>{{ state.name }}</strong>
	                    </h2>
	                    <hr>
	                </div>
	                <div class="col-md-8">
	                    <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
	                    <iframe width="100%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll={{ state.statecapital.latitude}}, {{ state.statecapital.longitude}}&amp;spn=56.506174,79.013672&amp;t=m&amp;z=4&amp;output=embed"></iframe>
	                </div>
	                <div class="col-md-4">
	                    <p>Capital:
	                        <strong>{{ state.statecapital.name }}</strong>
	                    </p>
	                    <p>Capital Population:
	                        <strong>{{ state.statecapital.capital_population }}</strong>
	                    </p>

	                </div>
	                <div class="clearfix"></div>
	            </div>
	    </div>
	</div>
	


{% endblock %}

main/templates/state_list.html
{% extends 'base.html' %}

{% block body %}


	<div class='container'>


        {% for state in states %}

        	<div class='row'>
        	<div class='box'>
        		<div class='col-lg-12 text-center'>

            		<h1 class='brand-name'><a href='/state_detail/{{state.pk}}'>{{ state.name }}</a></h1>
            		<hr class='tagline-divider'>
            		<h2>
            			<small>
            			{% for city in state.city_set.all|slice:":10" %}            			
            				{{ city.name }}
        			{% endfor %}
        			</small>
        			</h2>
        		</div>
        	</div>
        </div>

        {% endfor %}

    </div>

{% endblock %}